### ISSUE TITLE
How works with 2 device with same buttons

### ISSUE THREAD

**Issue by Mte90** [cyber-sushi/makima#1]
I mean I have a Razer https://www.razer.com/it-it/gaming-keypads/razer-tartarus-v2 that as you can see has a mouse scroll that I want to map different just for this device.
Also has different buttons that are the same for a keyboard but I want to map to different buttons and don't create conflicts.

**Comment by cyber-sushi** [comment]
Makima only scans for devices that are recognized as gamepads/joysticks.
You can see if a device is recognized as such by using `udevadm info /dev/input/eventX`, where X is the device number as shown in `evtest`, and checking if `ID_INPUT_JOYSTICK` is set to 1 for that device.
So it will not conflict with your other devices such as mice and keyboards (they're just ignored), **but** I'm not sure that the Razer Tartarus V2 is recognized as a gamepad by the Linux kernel, you'd have to check that as I don't have one.

Now that I think about it, I could expand the scope of this project to include other devices that are not gamepads, but it'll probably have to be specified by the user in the config file.

**Comment by cyber-sushi** [comment]
I have updated Makima to v0.2.0, it can now be used to remap any input device, so your Razer Tartarus should work as well.
As stated in the new Readme, you can also associate a specific config file to each device so you don't get conflicts.

I'm guessing that the Razer Tartarus is recognized as three different devices by Linux (a mouse, a keyboard and a controller, make sure to check that by running `evtest`) so you'll probably have to make three separate config files, each with the name of the device they're associated to, and put them in `~/.config/makima`.

I'm not closing this issue yet because there's still one feature that's missing, the capability to remap the mouse scroll wheel, which will be added in a future release.

**Comment by cyber-sushi** [comment]
Aaaand scroll wheel remapping is added with v0.2.1, I can close the issue
