### ISSUE TITLE
Controller button remapping bug: Scrolling gets assigned to keyboard buttons.

### ISSUE THREAD

**Issue by M4rtineski** [cyber-sushi/makima#24]
When I assign 'scroll up' and 'scroll down' to X and B buttons on the controller it gets assigned to my keyboard arrows instead while the controller buttons seem to do nothing. Here's the config:

```
[remap]
BTN_NORTH = ["KEY_SCROLLUP"] #X
BTN_EAST = ["KEY_SCROLLDOWN"] #B
BTN_SOUTH = ["KEY_R"] #A
BTN_WEST = ["KEY_L"] #Y
```

Otherwise other functions get assigned properly and don't affect the keyboard. Example:

```
[remap]
BTN_NORTH = ["KEY_U"] #X
BTN_EAST = ["KEY_D"] #B
BTN_SOUTH = ["KEY_R"] #A
BTN_WEST = ["KEY_L"] #Y
```

I'm trying to assign scrolling to those buttons because to me analog sticks feel very uncomfortable for this action compared to mouse scroll wheel or rotary encoders on my macrodeck.

**Comment by cyber-sushi** [comment]
Interesting, I'd be curious to see how the `KEY_SCROLLUP` and `KEY_SCROLLDOWN` events work, because I don't have a keyboard with those at hand to check, but I'm guessing they send a `1` event when pressed, a `2` event as long as they're held and then a `0` event when they're released, but Makima only sends a `1` event on press and a `0` event on release

I'll look into it, thank you for your report

**Comment by M4rtineski** [comment]
My macropad is via programmable so I can later assign those buttons (if they're available to assign) to it and test it out somehow. Is this scroll keycode something different from what scrollwheels use though? I was just searching for a way to scroll and found this.

**Comment by cyber-sushi** [comment]
Yes, they're two completely different types of event for the kernel

A scrollwheel emits _relative_ events with values 1 or -1 (up and down, there's no press or release), while `KEY_SCROLLUP` and `KEY_SCROLLDOWN` are _key_ events with values 0, 1 and possibly 2 (although I haven't tested this because I don't have a capable keyboard)

I think the solution would be implementing both scroll and cursor movements through keys, which would solve this issue and issue #23 

In any case, if you manage to bind `KEY_SCROLL*` to your macropad, feel free to post the output of `evtest` which could be useful regardless

**Comment by M4rtineski** [comment]
This is what happens with buttons assigned to the keyboard as stated in the issue:

![image](https://github.com/user-attachments/assets/75585124-835c-4ea3-be2c-e718c40f1df6)

As for my macropad it seems to use a mouse profile instead. I had to evtest the mouse profile of my macropad to be able to detect the scroll actions and they're relative like you said. (The via is a GUI fork of QMK so I don't have much control over what keycodes it uses. Their own keycodes seem to be named differently as well: https://docs.qmk.fm/keycodes)

Interestingly the scrolling button (on my macropad specifically) also has acceleration and is faster the longer I hold it. Didn't knew that because I use a rotary encoder for scrolling instead and it acts as a scrollwheel so you can't hold it like a button.

**Comment by M4rtineski** [comment]
> I think the solution would be implementing both scroll and cursor movements through keys, which would solve this issue and issue #23 

Wait, I just discovered that the KEY_SCROLL* acts differently from the scrolling I'm used to. It uses scrolling on the site without regard of the cursor's position which is not what I want.  Does scrollwheel scrolling have a keycode? I can't find anything in the "input event codes" file. :/

**Comment by cyber-sushi** [comment]
The scrollwheel's keycode is `REL_WHEEL` for vertical scroll and `REL_HWHEEL` for horizontal scroll, but since they're relative events and not key events, they can't be remapped as easily because event values for them work differently and they require ad-hoc code for each different event to be translated properly

Using Makima you can [remap some relative and absolute axis events](https://github.com/cyber-sushi/makima?tab=readme-ov-file#axis-events) to keys and combinations (e.g. you can remap scrollwheel-up to `KEY_UP`) and those in the docs are the ones that I manually implemented

What Makima can't do currently is the opposite, that is to say, remap keys/combinations to scroll and mouse movements (they're both relative events and they work similarly), which is what I'd like to do in order to solve this and the other issue

Anyway, thank you a lot for the feedback, I'm gonna implement this in the next few days

**Comment by M4rtineski** [comment]
I assume I can close this because I don't care for those buttons anymore (it's not what I needed anyway) and movement functionality got implemented. If it's something you want to fix then feel free to restore this issue.

**Comment by M4rtineski** [comment]
Hmmm, this would fit better I think. I with there was a "neutral" way of closing the issues.
